### ISSUE TITLE
Encoding and deployment

### ISSUE THREAD

**Issue by celiazut** [aroelke/deck-editor#1]
Hi, 
I’m really curious about your app ! 
I tried to deploy it (`mvn install`, then `mvn deploy`), but I had some encoding issues during deployment.

```
...
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
…
[ERROR] /.../deck-editor/MTG Deck Editor/src/editor/gui/CardTagPanel.java:[117,67] unmappable character for encoding UTF-8
…
```

I guess you’re using Windows OS, I tried on ubuntu with several encoding (UTF-8, ASCII, windows-1252…) but I doesn’t work.
I think that add encoding in `pom.xml` file could resolve the problem but I can’t find witch encoding… If by any chance you’ve got an idea about this issue.
Celia

**Comment by aroelke** [comment]
Thanks!  The code uses some UTF-8 characters that are out of range of ASCII, but I didn't realize that would break compatibility with other OSes.  I'll switch it to using \uXXXX notation so it should work.
